# QR Code Generator Configuration

# Output Options
output_pptx: true    # Generate PowerPoint presentation
output_pdf: true     # Generate PDF document
output_raw: true     # Generate raw QR code files in directories

# QR Code Settings
qr_error_correction: ERROR_CORRECT_L  # Options: ERROR_CORRECT_L, ERROR_CORRECT_M, ERROR_CORRECT_Q, ERROR_CORRECT_H
qr_box_size: 10      # Size of each box in the QR code
qr_border: 4         # Border size around the QR code

# Content Options
generate_descriptive_titles: true  # Try to generate descriptive titles from URLs